client_id = "eaef9487c803399e218ba4806b63d25d"
name = "ss inventry meneger"
application_url = "https://example.com"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_inventory,write_inventory,read_locations,read_markets_home,read_files,write_files"
[webhooks]
api_version = "2026-10"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[auth]
redirect_urls = [
  "https://example.com/api/auth"
]

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true